### ISSUE TITLE
python lib missing

### ISSUE THREAD

**Issue by ziermmar** [bitnami/bitnami-docker-mediawiki#57]
If you want to use the core extension "SyntaxHighlight_GeSHi", you're out of luck. It uses pygments, which needs python.

Solution:
If you add 'python' to the 'install_packages' line in your Dockerfile, SyntaxHighlight_GeSHi works.

**Comment by carrodher** [comment]
PR #58

**Comment by andrewhowdencom** [comment]
@carrodher suggest you talk even internally on the PR, so it's transparent.

**Comment by prydonius** [comment]
@carrodher I'm assuming we'll want to install python using `bitnami-pkg` instead of the `install_packages` command?

**Comment by andrewhowdencom** [comment]
@carrodher can we get an update on this? I just had a request internally about it ^^

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-mediawiki#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
