### ISSUE TITLE
openssl vulnerable version

### ISSUE THREAD

**Issue by mustafaarif** [bitnami/bitnami-docker-mediawiki#66]
**Description**
OpenSSL version (1.0.1t) on current image is outdated and is vulnerable. openssl reported vulnerabilities: https://www.openssl.org/news/vulnerabilities.html
I have update openssl by adding debian repos, but have found that apache is statically compiled with current openssl library and just updating openssl won't solve the issue.

**Before updating openssl**

root@9bfe180400b7:/# openssl version
OpenSSL 1.0.1t  3 May 2016

root@9bfe180400b7:/# ldd /opt/bitnami/apache/modules/mod_ssl.so
        linux-vdso.so.1 (0x00007ffe8f349000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007feb90c84000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007feb90888000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feb9066b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feb902cc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007feb900c8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007feb9112e000)

**Steps taken to update openssl**

docker exec -it mediawikicompose_mediawiki_1 /bin/sh -c "echo \"deb http://deb.debian.org/debian/ stable main contrib non-free\" >> /etc/apt/sources.list"
docker exec -it mediawikicompose_mediawiki_1 /bin/sh -c "echo \"deb http://deb.debian.org/debian/ stable-updates main contrib non-free\" >> /etc/apt/sources.list"
docker exec -it mediawikicompose_mediawiki_1 /bin/sh -c "echo \"deb http://deb.debian.org/debian-security stable/updates main\" >> /etc/apt/sources.list"

docker exec -it mediawikicompose_mediawiki_1 /bin/sh -c "apt-get update"

docker exec -it mediawikicompose_mediawiki_1 /bin/sh -c "apt-get upgrade"

**Test if latest openssl library is linked with apache**

Apache module mod_ssl should be able to link dynamically with latest openssl library, but its not the case.

root@9bfe180400b7:/# openssl version
OpenSSL 1.1.0f  25 May 2017

root@9bfe180400b7:/# ldconfig -p | grep ssl
        libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
        libssl.so.1.0.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0

root@9bfe180400b7:/# ldd /opt/bitnami/apache/modules/mod_ssl.so | grep ssl
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f53af0dc000)

root@9bfe180400b7:/usr/lib/x86_64-linux-gnu# mv libssl.so.1.0.0 old.libssl.so.1.0.0

root@9bfe180400b7:/usr/lib/x86_64-linux-gnu# ln -s libssl.so.1.1 libssl.so.1.0.0

root@9bfe180400b7:~# nami restart apache
nami    ERROR Unable to start com.bitnami.apache: httpd: Syntax error on line 135 of /opt/bitnami/apache/conf/httpd.conf: Cannot load modules/mod_ssl.so into server: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by /opt/bitnami/apache/modules/mod_ssl.so)

**Comment by beltran-rubo** [comment]
Debian Jessie latest version of OpenSSL is 1.0.1t-1+deb8u8 and it is compatible with mod_ssl.

`root@2532364b13b8:/# apt-get install openssl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  openssl
1 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Need to get 664 kB of archives.
After this operation, 74.8 kB disk space will be freed.
Get:1 http://security.debian.org/ jessie/updates/main openssl amd64 1.0.1t-1+deb8u8 [664 kB]
Fetched 664 kB in 0s (4998 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 7731 files and directories currently installed.)
Preparing to unpack .../openssl_1.0.1t-1+deb8u8_amd64.deb ...
Unpacking openssl (1.0.1t-1+deb8u8) over (1.0.1t-1+deb8u7) ...
Setting up openssl (1.0.1t-1+deb8u8) ...`

The issue could be it is installing a new major version from a repo you added to the sources. I would suggest just run the "apt-get install openssl" into the container to get the latest fixed OpenSSL 10.1 compatible version.
