### ISSUE TITLE
Visual editor not working in sub-pages in MediaWiki 1.35

### ISSUE THREAD

**Issue by kachkaev** [bitnami/bitnami-docker-mediawiki#84]
**Description**

**Steps to reproduce the issue:**

1. Create a new Mediawiki instance (I’ve done so via the [Helm Chart](https://hub.helm.sh/charts/bitnami/mediawiki))

1. Enable [Visual Editor](https://www.mediawiki.org/wiki/Extension:VisualEditor) in `LocalSettings.php`:
    ```php
    wfLoadExtension( 'VisualEditor' );
    $wgDefaultUserOptions['visualeditor-enable'] = 1;
    ```
1. Open the Visual Editor on the Main page or any other page without `/` in its title, confirm that it works.
1. Create a new page with a slash in its title (e.g. `Hello/World`) without using the Visual Editor
1. Start editing the new page with the Visual Editor.

**Describe the results you received:**

The following error shows up:

   > Error contacting the Parsoid/RESTBase server (HTTP 404)

<img width="700" alt="Screenshot 2020-10-01 at 21 49 47" src="https://user-images.githubusercontent.com/608862/94861975-40fa0300-0430-11eb-914a-2ddf14623667.png">

**Describe the results you expected:**

The page with `/` can be edited just as a top-level page (one without `/`)

**Additional information you deem important (e.g. issue happens only occasionally):**

Looks like this bug has been discussed in https://phabricator.wikimedia.org/T261921

https://www.mediawiki.org/wiki/Extension:VisualEditor has a FAQ section with a likely solution:

> **Error contacting the Parsoid/RESTBase server (HTTP 404) with Parsoid-PHP***
>  When the web server is Apache, it must be added `AllowEncodedSlashes NoDecode` in the VirtualHost section of the wiki (phabricator:T261921).

I could not verify the solution myself because I use the official bitnami image and `/opt/bitnami/apache/conf/vhosts/mediawiki-vhost.conf` gets reset on every container restart. Trying to make apache reload the config on the fly did not work for me, which is reasonable in production.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
irrelevant
```

- Output of `docker-compose version` (if applicable):

```
not applicable
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Official helm chart 10.0.8

**Comment by dani8art** [comment]
Hi @kachkaev thanks for opening the issue.

I think you can try one of these methods in order to get this working https://github.com/bitnami/bitnami-docker-mediawiki#customize-this-image

**Comment by kachkaev** [comment]
Hi @dani8art, thanks for paying attention to this issue! I tried customising the contents of the image for a couple hours yesterday, but failed in this so far. Because I'm deploying the container to k8s via a helm chart, it's not that easy to mount an extra file.

I can take another look, but probably this will need to wait for a few days because of the deadline I’ve got. Happy to share the results of my investigation here later if the issue remains unsolved.

**Comment by kachkaev** [comment]
A small update folks 👋

Since I have two instances of the wiki running, I could test if my hypothesis about `AllowEncodedSlashes NoDecode` is correct or not by hacking the sandbox.

So I went to the k8s dashboard and first manually created a config map:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-vhost
  namespace: my-namespace
data:
  file: |-
    <VirtualHost 127.0.0.1:8080 _default_:8080>
      ServerAlias *
      DocumentRoot /opt/bitnami/mediawiki
      AllowEncodedSlashes NoDecode
      <Directory "/opt/bitnami/mediawiki">
        Options -Indexes +FollowSymLinks -MultiViews
        AllowOverride None
        Require all granted
        RewriteEngine On
        RewriteRule ^/?wiki(/.*)?$ %{DOCUMENT_ROOT}/index.php [L]
      </Directory>
      Include "/opt/bitnami/apache/conf/vhosts/htaccess/mediawiki-htaccess.conf"
    </VirtualHost>
```

↑ The contents of this file were the same as what I saw in `/opt/bitnami/apache/conf/vhosts/httpd.conf` for a live MediaWiki pod. The only added line was `AllowEncodedSlashes NoDecode` as suggested in [Extension:VisualEditor#Troubleshooting](https://www.mediawiki.org/wiki/Extension:VisualEditor#Troubleshooting).

Second, I went to the definition of my deployment and mounted the config map like so:

```yaml
# ...
spec:
  template:
    spec:
      volumes:
        - name: test-configmap
          configMap:
            name: custom-vhost
        # ...
      containers:
        - name: mediawiki
           volumeMounts:
            - name: test-configmap
              mountPath: /opt/bitnami/apache/conf/vhosts/httpd.conf
              subPath: file
          # ...
```

Finally, after I saved the definition of the MediaWiki deployment, the pod got recreated and I confirmed the presence of `AllowEncodedSlashes NoDecode` in `/opt/bitnami/apache/conf/vhosts/httpd.conf`. Visual editor for pages with slashes worked!

The hack I’ve applied will be wiped out the next time I re-deploy the chart, which makes it far from perfect. Although the solution is still better then nothing, applying it to the Docker image itself can save a lot of time for other MediaWiki users.

From MediaWiki 1.35, VisualEditor is a part of the default distribution, so it’s not unreasonable to expect it to work right away after enabling it in `LocalSettings.php`.

 Hope my investigation helped!

**Comment by dani8art** [comment]
Hi @kachkaev, that's really great! A very cool solution to the problem.

Thank you for the suggestion, it could be interesting to support this feature as you said it could be very useful to other MediaWiki users. We have opened an internal task in order to evaluate it, unfortunately, due to there is a way to configure the container and regarding priorities and internal milestones we can't give you an ETA. However, if it is important for you and you feel you can handle it and you have a chance to create a PR we would be happy to handle it.

**Comment by kachkaev** [comment]
not stale

**Comment by kachkaev** [comment]
not stale

**Comment by rednevals** [comment]
Definitely not stale... Still an issue with 1.36 when using Docker Compose locally. Would this be an issue when deployed in AWS?

**Comment by carrodher** [comment]
This issue is still open since a solution was not provided, can you try the above proposed workaround? Regarding the platform, as the issue is related to the container image, it will appear in the different platforms where the container is deployed, it shouldn't matter if it is via docker-compose or AWS

Since the `on-hold` label was added this issue is not going to be closed, that is the purpose of the `stale` label.

**Comment by rednevals** [comment]
This issue is happening for me even on just a top level page without '/' in the path. I'm currently testing this locally:

Windows 10 Pro + WSL 2 + Docker Desktop + VS Code

Are you saying that this will not be an issue when deployed in AWS?

**Comment by carrodher** [comment]
No, sorry for the misunderstanding. If the issue is related to the container image you will find it in any platform (locally, AKS, EKS, docker-compose, k8s, etc)

**Comment by rednevals** [comment]
Ok. Thanks for responding. That is unfortunate. I have an EC2 instance that I created manually using the Bitnami MediaWiki AMI and it does not have this issue. I was hoping to be able to use Docker Compose, etc...

**Comment by carrodher** [comment]
Probably there is some room for improvement in the following logic, https://github.com/bitnami/bitnami-docker-mediawiki/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/mediawiki/postunpack.sh#L46. On our side there is an internal task, but due to other priorities in the team, we didn't find the bandwidth to work on that. As the code is opensource, if someone wants to contribute we will be happy to review it, otherwise, we will need to wait until the internal task is done but I can't provide an ETA

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-mediawiki#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.

**Comment by go2tom42** [comment]
not stale
